export { ReactComponent as FoodIcon1 } from './food1.svg'
export { ReactComponent as FoodIcon2 } from './food2.svg'
export { ReactComponent as HeartIcon } from './heart.svg'
export { ReactComponent as SearchIcon } from './search.svg'
export { ReactComponent as ThinSearchIcon } from './search-thin.svg'
